In [6]:
import numpy as np

array1=np.arange(12)
array1.size
array1.shape

#改辦ndarray的形狀
array2=array1.reshape(3,4)
print(array2)
print(array2[2,1])  #列(row),行(column)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
9
